### ISSUE TITLE
Not getting value only

### ISSUE THREAD

**Issue by shawngiese** [Socvest/streamlit-local-storage#1]
When I run 
get_item = localS.getItem("mykey") 

I get 
{'storage': {'item': 'mykey', 'value': ...

I thought I would get just the value from the key.

**Comment by Socvest** [comment]
Hmmm... you are right, it seems I complicated the delivery of the data. In essence, it is a dictionary highlighting that you have received a result that is in storage but also as a dictionary. I will amend.

**Comment by Socvest** [comment]
Please review the latest update.

**Comment by Socvest** [comment]
Closing as this has been rectified.
