### ISSUE TITLE
Just a general query

### ISSUE THREAD

**Issue by piyushK52** [Socvest/streamlit-local-storage#3]
Your streamlit component is successfully able to read and write from the localstorage but when I use vanilla js to read and write from the localstorage, it doesn't work (you can check this https://github.com/piyushK52/streamlit_globalrefresh/blob/main/streamlit_globalrefresh/frontend/src/index.ts).. Any idea as to why this happens? (I am talking about localStorage.setItem and localStorage.getItem)

**Comment by Socvest** [comment]
Thanks.

Whenever you use vanilla localStorage.setItem, the component/iframe needs to remount before the changes are recognised by streamlit. Hence why I used `import useLocalStorageState from 'use-local-storage-state'` library as it does this automatically.

**Comment by piyushK52** [comment]
Ah.. got it. Thanks.
